name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./.github/actions/my-action
        with:
          repo: Repo2
          workflow_file_name: master.yml
          
